"""empty message

Revision ID: 5133e83279dd
Revises: 78ec0581725d
Create Date: 2023-01-31 19:08:03.053730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5133e83279dd'
down_revision = '78ec0581725d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statuses', 'name',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=128), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'email')
    op.alter_column('statuses', 'name',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
